# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EpicMixGuestGPSData',
                'doc_host': 'https://JeremyDemlow.github.io',
                'git_url': 'https://github.com/JeremyDemlow/EpicMixGuestGPSData',
                'lib_path': 'EpicMixGuestGPSData'},
  'syms': {'EpicMixGuestGPSData.core': {'EpicMixGuestGPSData.core.foo': ('core.html#foo', 'EpicMixGuestGPSData/core.py')}}}