# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EpicMixGuestGPSData',
                'doc_host': 'https://JeremyDemlow.github.io',
                'git_url': 'https://github.com/JeremyDemlow/EpicMixGuestGPSData',
                'lib_path': 'EpicMixGuestGPSData'},
  'syms': { 'EpicMixGuestGPSData.poc_gps': { 'EpicMixGuestGPSData.poc_gps.create_circle_area_around_lifts': ( 'gps_poc.html#create_circle_area_around_lifts',
                                                                                                              'EpicMixGuestGPSData/poc_gps.py'),
                                             'EpicMixGuestGPSData.poc_gps.kml2csv': ( 'gps_poc.html#kml2csv',
                                                                                      'EpicMixGuestGPSData/poc_gps.py'),
                                             'EpicMixGuestGPSData.poc_gps.process_coordinate_string': ( 'gps_poc.html#process_coordinate_string',
                                                                                                        'EpicMixGuestGPSData/poc_gps.py')}}}