# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_GPS_POC.ipynb.

# %% auto 0
__all__ = ['snowflake_poc_table_grab']

# %% ../nbs/00_GPS_POC.ipynb 4
def snowflake_poc_table_grab(sf_connection):
    "Grab the data from a snowflake to allow for play on GPS Data"
    return f'Hello {sf_connection}!'
